
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ld=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch(e){return d}};
const sv=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
let mem={};const get=(k,d)=>k in mem?mem[k]:(mem[k]=ld(k,d));const put=(k,v)=>{mem[k]=v;sv(k,v)};
const T=(id,name,desc,f)=>({id,name,desc,f});
const TYPES=[
T('whitelist','Whitelist','Required to join the city.',[['char','Character name','t'],['exp','Roleplay experience','s',['New','1–2 years','3+ years']],['story','Character backstory','a'],['why','Why Resistenza?','a']]),
T('char','Character approval','Get a new character cleared.',[['char','Character name','t'],['origin','Origin / hometown','t'],['story','Backstory','a'],['goal','Character goals','a']]),
T('police','Police department','Join the force.',[['char','Character name','t'],['prior','Previous LEO roleplay','a'],['scn','You find an armed suspect fleeing. What do you do?','a']]),
T('ems','EMS / Fire','Save lives in the city.',[['char','Character name','t'],['prior','Previous medical roleplay','a'],['scn','Describe how you handle a multi-victim crash.','a']]),
T('business','Business','Open a shop, club or garage.',[['biz','Business name','t'],['kind','Type','s',['Restaurant','Garage','Club','Retail','Other']],['plan','Business plan','a'],['staff','Planned staff size','n']]),
T('crew','Gang / crew','Register a criminal organization.',[['crew','Crew name','t'],['size','Starting members','n'],['lore','Lore and story','a'],['goals','Goals and planned scenes','a']]),
T('staff','Staff','Help run the community.',[['tz','Timezone','t'],['hrs','Hours per week','n'],['exp','Moderation experience','a'],['scn','A player disputes a ban. How do you respond?','a']]),
T('appeal','Ban appeal','Ask for a second chance.',[['banid','Ban ID or date','t'],['reason','Reason you were banned','a'],['chg','What will you do differently?','a']]),
T('report','Player report','Report rule-breaking.',[['who','Reported player ID','t'],['date','Date of incident','t'],['rule','Rule broken','t'],['ev','Evidence link','t'],['det','What happened','a']]),
T('ticket','Support ticket','Technical or account help.',[['sub','Subject','t'],['det','Describe the issue','a']]),
T('partner','Partnership','Streamers and communities.',[['org','Name / channel','t'],['link','Link','t'],['pitch','Proposal','a']])
];
const BASE=TYPES.slice();const syncT=()=>{TYPES.length=BASE.length;L(settings().dp).forEach(d=>TYPES.push(T('x'+d[0].toLowerCase().replace(/\W/g,''),d[0],d[1]||'',(d[2]||'Details').split(';').map((f,i)=>['f'+i,f.trim(),'a']))))};
const SET0={name:'Resistenza RP',discord:'https://discord.gg/ymyYfugAv',ip:'connect play.resistenza.gg',pass:'admin123',closed:[],ru:'General conduct | Respect every player and staff member.\nGeneral conduct | No hate speech, harassment or discrimination.\nGeneral conduct | No cheating, exploits or third-party advantages.\nGeneral conduct | Voice roleplay is required in the city.\nRoleplay fundamentals | Fear RP: value your life when threatened.\nRoleplay fundamentals | No metagaming: only use what your character knows.\nRoleplay fundamentals | No powergaming or forcing outcomes.\nRoleplay fundamentals | No RDM or VDM. Every fight needs a roleplay reason.\nRoleplay fundamentals | New Life Rule applies after character death.\nCriminal activity | Register your crew before running organized crime.\nCriminal activity | Big crimes need enough police on duty.\nCriminal activity | Cooldowns apply between major crimes.\nPolice and EMS | Follow your department chain of command.\nPolice and EMS | No corruption without staff approval.\nPolice and EMS | EMS are neutral and must never be targeted.',il:'Crews and gangs | Register your organization, set a story and recruit members.\nHeists and robberies | Planned scores that need enough police on duty.\nBlack market | Trade, smuggle and launder through player-run fronts.\nTurf wars | Territory conflicts that must have roleplay behind them.',gr:'Example Crew | Leader name | 6',sh:'Supporter Pack | 10 USD | A perk and a spot on the supporters wall.\nPriority Queue | 5 USD | Skip the connect queue on busy nights.',pm:'Bank or wallet | Add your payment instructions in Admin, Payment Gateway.',dp:'',pl:0,mx:128,dm:0,ev:'Oct 18 | City Grand Opening | Opening night with a live car meet and giveaways.\nNov 01 | Heist Weekend | Crews compete for the biggest score of the season.',tm:'Your Name | Owner\nStaff Member | Head Admin\nStaff Member | Moderator',st:''};
const settings=()=>({...SET0,...get('s_set',{})});
const apps=()=>get('s_apps',[]);
const toast=m=>{const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.append(t);setTimeout(()=>t.remove(),2200)};
const isAdmin=()=>sessionStorage.getItem('adm')==='1'||mem.adm===1;
const fmt=t=>new Date(t).toLocaleString([], {dateStyle:'medium',timeStyle:'short'});
const badge=s=>`<span class="badge ${s}">${s}</span>`;

function nav(r){
  const L=[['home','Home'],['events','Events'],['rules','Rules'],['apply','Applications'],['team','Team'],['streamers','Streamers'],['illegal','Illegal'],['store','Store'],['gangs','Gangs'],['support','Support']];
  $('#nav').innerHTML=`<span class="logo"><b class="lm"></b>${esc(settings().name)}</span>`+L.map(([k,v])=>`<a href="#${k}" class="${r==k||(k=='apply'&&r=='status')?'on':''}">${v}</a>`).join('')+`<a class="dcn" href="${esc(dcu())}" target="_blank" rel="noopener" aria-label="Join our Discord">${DI}</a><a href="#admin" class="cta">${isAdmin()?'Admin':'Login'}</a>`;
}
const route=()=>{const h=location.hash.slice(1).split('/');const r=h[0]||'home';nav(r);syncT();$('#app').style.maxWidth=r=='admin'?'1280px':'';({home,apply,status,admin,events:pEv,rules:pRules,team:pTeam,streamers:pStr,store:pShop,gangs:pGang,illegal:pIll,support:pSup}[r]||home)(h[1]);window.scrollTo(0,0);fx();fx2()};
addEventListener('hashchange',()=>{const w=$('#wipe');if(RM||!w)return route();w.className='in';setTimeout(()=>{route();w.className='out'},280)});

const P={whitelist:"M5 5h14a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2z|M7 11a2 2 0 104 0 2 2 0 10-4 0|M6 16c.6-1.6 1.8-2.4 3-2.4s2.4.8 3 2.4|M14 10h4|M14 13h4",char:"M4 6c3 1 5 1 8 1s5 0 8-1v6c0 4-3.5 7-8 7s-8-3-8-7z|M8 11h2|M14 11h2|M9.5 15c1.5 1 3.5 1 5 0",police:"M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z|M12 8.5l1 2 2.2.3-1.6 1.5.4 2.2-2-1.1-2 1.1.4-2.2-1.6-1.5 2.2-.3z",ems:"M9 4h6v5h5v6h-5v5H9v-5H4V9h5z",business:"M3 9l1.5-5h15L21 9z|M5 9v11h14V9|M10 20v-5h4v5",crew:"M12 3c-4 0-7 3-7 7v11h14V10c0-4-3-7-7-7z|M9 11c0-1.5 1.3-2.5 3-2.5s3 1 3 2.5-1.3 3.5-3 3.5-3-2-3-3.5z",staff:"M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z|M9 12l2 2 4-4",appeal:"M12 4v16|M7 20h10|M5 7h14|M5 7l-3 7a3 3 0 006 0z|M19 7l-3 7a3 3 0 006 0z",report:"M5 21V4|M5 4h12l-2 4 2 4H5",ticket:"M3 7h18v3a2 2 0 000 4v3H3v-3a2 2 0 000-4z|M14 7v10",partner:"M10 14a4 4 0 005.7 0l3-3a4 4 0 00-5.7-5.7l-1 1|M14 10a4 4 0 00-5.7 0l-3 3a4 4 0 005.7 5.7l1-1",home:"M3 11l9-8 9 8|M5 10v10h14V10|M10 20v-5h4v5",cam:"M3 7h4l2-3h6l2 3h4v12H3z|M8.5 13a3.5 3.5 0 107 0 3.5 3.5 0 10-7 0"};
const IC={};for(const k in P)IC[k]=`<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${P[k].split("|").map(d=>`<path pathLength="1" d="${d}"/>`).join("")}</svg>`;
function sky(){
const R=n=>{n=Math.sin(n*127.1)*43758.5453;return n-Math.floor(n)};
const lay=(sd,y0,hm,hv,fill,win,par)=>{let g='',x=-10,i=0;while(x<1210){const w=30+R(sd+i)*60,h=hm+R(sd+i+9)*hv,y=y0-h;g+=`<rect x="${x}" y="${y}" width="${w}" height="${h+60}" fill="${fill}"/>`;if(R(sd+i+3)>.7)g+=`<rect x="${x+w/2-1}" y="${y-18}" width="2" height="18" fill="${fill}"/>`;if(win)for(let j=0;j<h/16;j++)for(let k=0;k<w/12;k++){const r=R(sd+i*13+j*7+k);if(r>.62)g+=`<rect class="w${r>.93?' f':''}" x="${x+4+k*12}" y="${y+6+j*16}" width="5" height="7" fill="${r>.8?'#ffffff':'#bdbdbd'}" opacity=".8"/>`}x+=w+R(sd+i)*6;i++}return `<g style="transform:translateY(calc(var(--sy,0)*${par}px))">${g}</g>`};
let st='';for(let i=0;i<55;i++)st+=`<circle class="st" cx="${R(i)*1200}" cy="${R(i+50)*170}" r="${.6+R(i+99)*1.1}" fill="#fff" style="animation-delay:${R(i+7)*3}s"/>`;
const car=(y,d,dl,rev)=>`<g class="car${rev?' rv2':''}" style="animation-duration:${d}s;animation-delay:${dl}s"><rect x="0" y="${y}" width="46" height="9" rx="4" fill="#05050a"/><rect x="${rev?-60:46}" y="${y+2}" width="60" height="5" fill="url(#${rev?'tl':'hl'})"/><rect x="${rev?46:-22}" y="${y+2}" width="22" height="5" fill="url(#${rev?'hl':'tl'})" transform="${rev?'':'scale(1)'}"/></g>`;
return `<svg class="sky" viewBox="0 0 1200 400" role="img" aria-label="City skyline at night with moving traffic"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#050505"/><stop offset=".5" stop-color="#262626"/><stop offset=".8" stop-color="#5c5c5c"/><stop offset="1" stop-color="#d0d0d0"/></linearGradient><radialGradient id="m"><stop offset="0" stop-color="#fff" stop-opacity=".9"/><stop offset=".25" stop-color="#ffffff" stop-opacity=".35"/><stop offset="1" stop-color="#ffffff" stop-opacity="0"/></radialGradient><linearGradient id="hl"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient><linearGradient id="tl"><stop offset="0" stop-color="#9a9a9a" stop-opacity="0"/><stop offset="1" stop-color="#9a9a9a"/></linearGradient><linearGradient id="fog" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#d0d0d0" stop-opacity="0"/><stop offset="1" stop-color="#d0d0d0" stop-opacity=".35"/></linearGradient></defs><rect width="1200" height="400" fill="url(#g)"/>${st}<circle cx="900" cy="120" r="150" fill="url(#m)"/><circle cx="900" cy="120" r="30" fill="#ffffff"/>${lay(1,330,60,120,'#2e2e2e',0,.09)}${lay(40,340,50,150,'#181818',1,.05)}<rect y="230" width="1200" height="110" fill="url(#fog)"/>${lay(90,350,40,170,'#050505',1,.02)}<rect y="345" width="1200" height="55" fill="#05050a"/><rect y="345" width="1200" height="2" fill="#ffffff" opacity=".5"/><rect y="372" width="1200" height="2" fill="#fff" opacity=".18" stroke-dasharray="26 22"/>${car(354,9,0,0)}${car(354,13,-6,0)}${car(380,11,-2,1)}${car(380,7,-5,1)}</svg>`}
function home(){
  const s=settings(),n=apps().length;
  const way=[[IC.police,'Law enforcement','Patrol, investigate and climb a real chain of command.'],[IC.ems,'Medical and fire','Dispatch-driven calls with full treatment roleplay.'],[IC.business,'Business owners','Run a garage, club or restaurant with payroll and stock.'],[IC.crew,'Crews and gangs','Registered crews with story-driven conflict.'],[IC.home,'Civilians','Rent an apartment, take a job, build a name.'],[IC.cam,'Creators','Streamer perks and a partner program.']];
  const rules=['Stay in character; OOC only when needed','No RDM, VDM or combat logging','Value your life when threatened','No metagaming or powergaming','New Life Rule after character death','No hate speech, harassment or cheats','One ban appeal per decision'];
  const faq=[['Do I need a microphone?','Yes. Voice roleplay is required in the city.'],['How long does whitelist review take?','Staff aim to answer within 48 hours. Track yours with your ID.'],['Can I run more than one character?','Yes, once your first character is approved.'],['Is the server free?','Yes. Perks are cosmetic only.']];
  $('#app').innerHTML=`
  <section class="hero"><div class="emb" role="img" aria-label="Resistenza Roleplay logo"><i></i></div><span class="pill"><i class="dot"></i>Server online · Whitelist open</span>
  <h1>Join the<br><em>${esc(s.name.replace(/ RP$/,''))}.</em></h1>
  <p>A serious, whitelisted roleplay city with custom jobs, a player-run economy and staff who answer every ticket.</p>
  <div class="row"><a class="btn" href="#apply/whitelist">Join The Whitelist</a>${DL()}</div>
  <div class="stats"><div class="chip"><b>${esc(s.ip)}</b><span>connect in F8</span></div><div class="chip"><b>128</b><span>player slots</span></div><div class="chip"><b>${TYPES.length}</b><span>application types</span></div><div class="chip"><b>${n}</b><span>applications received</span></div></div>
  ${sky()}</section><div class="tick"><div>${["WHITELISTED","CUSTOM ECONOMY","REAL JOBS","VOICE ROLEPLAY","24/7 STAFF","NO P2W"].map(x=>`<span>${x}</span>`).join("").repeat(2)}</div></div>
  <section class="sec"><h2>The city is awake</h2><p>Live snapshot of the server.</p><div class="card live"><div class="grid"><div><span class="note">STATUS</span><b><i class="dot"></i>ONLINE</b></div><div><span class="note">PLAYER COUNT</span><b>${s.pl} / ${s.mx}</b></div><div><span class="note">DISCORD MEMBERS</span><b>${s.dm||'--'}</b></div></div><p style="margin:16px 0 8px" class="note">SERVER IP</p><div class="row"><code class="ip">${esc(s.ip)}</code><button class="btn s" onclick="cp()">Copy server IP</button>${DL()}</div></div></section>
  <section class="sec"><h2>Our philosophy</h2><p>We don't just run a server. We build a resistance.</p><div class="card"><p style="margin:0 0 14px;font-size:17px;color:var(--tx)">${esc(s.name)} is a community built on realism and immersion. Fair systems, an active staff team and a respectful player base give every story room to grow, and every action shapes the city.</p><div class="row">${['ACTIVE STAFF','FAIR SYSTEMS','RESPECTFUL COMMUNITY','HIGH IMMERSION','PERSISTENT WORLD'].map(x=>`<span class="tag">${x}</span>`).join('')}</div></div></section>
  <section class="sec"><h2>Pick your path</h2><p>Every role has its own application and training.</p><div class="grid">${way.map(w=>`<div class="card hv"><div class="ic">${w[0]}</div><h3>${w[1]}</h3><p style="margin:0">${w[2]}</p></div>`).join('')}</div></section>
  <section class="sec"><h2>How to join</h2><p>Three steps from applicant to resident.</p><div class="grid">${[['1','Apply','Fill in the whitelist form with your character story.'],['2','Get reviewed','Staff read it and leave notes you can see.'],['3','Connect','Join voice, pick up your keys and start playing.']].map(a=>`<div class="card step"><b>${a[0]}</b><h3>${a[1]}</h3><p style="margin:0">${a[2]}</p></div>`).join('')}</div></section>
  <section class="sec"><h2>City rules</h2><p>Short, fair and enforced.</p><div class="rg">${rules.map(r=>`<div>${r}</div>`).join('')}</div></section>
  <section class="sec"><h2>Questions</h2>${faq.map(f=>`<details><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join('')}</section>
  <footer><span><b class="lm"></b>${esc(s.name)} · Not affiliated with Rockstar Games</span><a href="${esc(dcu())}" target="_blank" rel="noopener" style="text-decoration:none">${DI} Join our Discord</a></footer>`;
}

function apply(id){
  const s=settings();
  if(!id){
    $('#app').innerHTML=`<h2 style="margin-top:12px">Applications</h2><p class="note">Pick a type. You get a tracking ID after sending. <a href="#status">Check an application</a></p><div class="grid">${TYPES.map(t=>{const c=s.closed.includes(t.id);return `<div class="card hv"><div class="ic">${IC[t.id]||IC.whitelist}</div><h3>${t.name}</h3><p>${t.desc}</p>${c?badge('closed'):`<a class="btn s" href="#apply/${t.id}">Start application</a>`}</div>`}).join('')}</div>`;return}
  const t=TYPES.find(x=>x.id==id);if(!t){location.hash='apply';return}
  if(s.closed.includes(id)){$('#app').innerHTML=`<h2>${t.name} is closed</h2><p>We are not taking these right now. Check back soon.</p><a class="btn g" href="#apply">Back to applications</a>`;return}
  const fld=([k,l,ty,o])=>`<label for="f_${k}">${esc(l)}</label>`+(ty=='a'?`<textarea id="f_${k}" required></textarea>`:ty=='s'?`<select id="f_${k}">${o.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`:`<input id="f_${k}" type="${ty=='n'?'number':'text'}" required>`);
  $('#app').innerHTML=`<a href="#apply" class="note">← All applications</a><h2 style="margin-top:8px">${t.name} application</h2>
  <div class="card" style="max-width:640px"><label for="f_discord">Discord username</label><input id="f_discord" required>
  <label for="f_age">Age</label><input id="f_age" type="number" min="1" required>
  ${t.f.map(fld).join('')}
  <label><input type="checkbox" id="f_rules" style="width:auto;margin-right:8px">I have read the server rules and my answers are my own.</label>
  <p><button class="btn" id="go">Send application</button></p></div>`;
  $('#go').onclick=()=>{
    const data={},lab={discord:'Discord',age:'Age'};
    for(const [k,l] of [['discord'],['age'],...t.f]){const el=$('#f_'+k);if(!el.value.trim()){el.focus();return toast('Fill in every field')}data[k]=el.value.trim()}
    if(+data.age<13)return toast('You must be 13 or older');
    if(!$('#f_rules').checked)return toast('Confirm you read the rules');
    const code='RS-'+Math.random().toString(36).slice(2,7).toUpperCase();
    const labels={discord:'Discord',age:'Age'};t.f.forEach(f=>labels[f[0]]=f[1]);
    put('s_apps',[{id:code,type:t.id,typeName:t.name,status:'pending',at:Date.now(),data,labels,note:''},...apps()]);
    burst();$('#app').innerHTML=`<h2>Application sent</h2><p>Your tracking ID is</p><h1 style="color:var(--ac);font-size:56px">${code}</h1><p class="note">Save this ID. Use Check status to see the decision and staff notes.</p><a class="btn" href="#status/${code}">Track it</a>`};
}

function status(id){
  $('#app').innerHTML=`<h2 style="margin-top:12px">Check application</h2><div class="row"><input id="sid" placeholder="RS-XXXXX" style="max-width:260px" value="${esc(id||'')}"><button class="btn" id="sg">Look up</button></div><div id="sres" style="margin-top:20px"></div>`;
  const run=()=>{const q=$('#sid').value.trim().toUpperCase();if(!q)return;const a=apps().find(x=>x.id==q);
    $('#sres').innerHTML=a?`<div class="card"><h3>${esc(a.typeName)} ${badge(a.status)}</h3><p>Sent ${fmt(a.at)}</p>${a.note?`<p><b>Staff note:</b> ${esc(a.note)}</p>`:'<p>No staff note yet.</p>'}</div>`:`<p>No application found with that ID. Check the code and try again.</p>`};
  $('#sg').onclick=run;if(id)run();
}

const DI='<svg class="di" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189z"/></svg>';
const dcu=()=>{const d=settings().discord||'';return /^https?:/.test(d)?d:'https://'+d};
const DL=()=>`<a class="btn g" href="${esc(dcu())}" target="_blank" rel="noopener">${DI} Join Discord</a>`;
const L=t=>String(t||'').split('\n').map(l=>l.split('|').map(x=>x.trim())).filter(a=>a[0]);
const cp=()=>{const t=settings().ip.replace(/^connect /,'connect ');try{navigator.clipboard.writeText(t).then(()=>toast('Server IP copied'),()=>toast(t))}catch(e){toast(t)}};
const pg=(t,d,b)=>`<h2 style="margin-top:12px">${t}</h2><p class="note">${d}</p>${b}`;
function pEv(){const E=L(settings().ev);$('#app').innerHTML=pg('Events','Community nights, tournaments and city-wide storylines.',`<div class="grid">${E.length?E.map(e=>`<div class="card hv"><span class="badge pending">${esc(e[0])}</span><h3 style="margin-top:10px">${esc(e[1])}</h3><p style="margin:0">${esc(e[2]||'')}</p></div>`).join(''):'<p>No events scheduled yet.</p>'}</div><p style="margin-top:18px">${DL()}</p>`)}
function pRules(){const G={};L(settings().ru).forEach(a=>(G[a[0]]=G[a[0]]||[]).push(a[1]||''));
$('#app').innerHTML=pg('Rules','Read these before you connect. Staff decisions can be appealed once.',Object.entries(G).map(([k,v],i)=>`<details ${i?'':'open'}><summary>${esc(k)}</summary><div class="rg" style="margin-top:12px">${v.map(x=>`<div>${esc(x)}</div>`).join('')}</div></details>`).join('')+`<p style="margin-top:18px"><a class="btn" href="#apply/whitelist">Join The Whitelist</a></p>`)}
function pTeam(){const T=L(settings().tm);$('#app').innerHTML=pg('Team','The people keeping the city fair and alive.',`<div class="grid">${T.map(t=>`<div class="card hv"><div class="ic" style="font:800 20px Archivo;border-radius:50%">${esc(t[0][0].toUpperCase())}</div><h3>${esc(t[0])}</h3><p style="margin:0">${esc(t[1]||'')}</p></div>`).join('')}</div><p style="margin-top:18px"><a class="btn" href="#apply/staff">Apply for staff</a></p>`)}
function pStr(){const S=L(settings().st);$('#app').innerHTML=pg('Streamers','Watch the city live, or join the partner program.',`<div class="grid">${S.length?S.map(t=>`<div class="card hv"><div class="ic">${IC.cam}</div><h3>${esc(t[0])}</h3><p>Live roleplay on the server.</p><a class="btn s" href="${esc(t[1]||'#')}" target="_blank" rel="noopener">Watch</a></div>`).join(''):'<p>No streamers listed yet.</p>'}</div><p style="margin-top:18px"><a class="btn" href="#apply/partner">Become a partner</a></p>`)}
function pIll(){const I=[['crew','Crews and gangs','Register your organization, set a story and recruit members.'],['report','Heists and robberies','Planned scores that need enough police on duty.'],['business','Black market','Trade, smuggle and launder through player-run fronts.'],['police','Turf wars','Territory conflicts that must have roleplay behind them.']];
$('#app').innerHTML=pg('Illegal','Crime has rules here. Story first, loot second.',`<div class="grid">${I.map(i=>`<div class="card hv"><div class="ic">${IC[i[0]]}</div><h3>${i[1]}</h3><p style="margin:0">${i[2]}</p></div>`).join('')}</div><p style="margin-top:18px"><a class="btn" href="#apply/crew">Register your crew</a></p>`)}
function pIll(){const K=['crew','report','business','police'];
$('#app').innerHTML=pg('Illegal','Crime has rules here. Story first, loot second.',`<div class="grid">${L(settings().il).map((i,k)=>`<div class="card hv"><div class="ic">${IC[K[k%4]]}</div><h3>${esc(i[0])}</h3><p style="margin:0">${esc(i[1]||'')}</p></div>`).join('')}</div><p style="margin-top:18px"><a class="btn" href="#apply/crew">Register your crew</a></p>`)}
function pGang(){$('#app').innerHTML=pg('Gang rosters','Registered crews operating in the city.',`<div class="grid">${L(settings().gr).map(g=>`<div class="card hv"><div class="ic">${IC.crew}</div><h3>${esc(g[0])}</h3><p style="margin:0">Leader: ${esc(g[1]||'-')}<br>Members: ${esc(g[2]||'-')}</p></div>`).join('')||'<p>No crews registered yet.</p>'}</div><p style="margin-top:18px"><a class="btn" href="#apply/crew">Register your crew</a></p>`)}
const ORD=()=>get('s_ord',[]);
const wallH=()=>{const W=ORD().filter(o=>o.status=='verified');return W.length?`<div class="grid">${W.map(o=>`<div class="card"><h3>${esc(o.name)}</h3><p style="margin:0">${esc(o.item)}${o.msg?` · "${esc(o.msg)}"`:''}</p></div>`).join('')}</div>`:'<p>No verified supporters yet. Be the first.</p>'};
function pShop(){const S=L(settings().sh),P=L(settings().pm);
$('#app').innerHTML=pg('Store','Support the server. Staff verify every order.',`<div class="grid">${S.map((x,i)=>`<div class="card hv"><div class="ic">${IC.business}</div><h3>${esc(x[0])}</h3><p>${esc(x[2]||'')}</p><div class="row"><b style="font:800 22px Archivo">${esc(x[1]||'')}</b><button class="btn s" data-b="${i}">Buy</button></div></div>`).join('')||'<p>The store is empty.</p>'}</div><div id="co"></div><section class="sec"><h2>Supporters wall</h2>${wallH()}</section>`);
document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{const x=S[b.dataset.b];
$('#co').innerHTML=`<div class="card" style="margin-top:16px;max-width:560px"><h3>Checkout: ${esc(x[0])} (${esc(x[1]||'')})</h3><label for="o1">Your name</label><input id="o1"><label for="o2">Discord username</label><input id="o2"><label for="o3">Payment method</label><select id="o3">${P.map(m=>`<option>${esc(m[0])}</option>`).join('')}</select><p class="note" id="pi"></p><label for="o4">Transaction reference</label><input id="o4"><label for="o5">Public message (optional)</label><input id="o5"><p><button class="btn" id="o6">Send order</button></p></div>`;
const sh=()=>$('#pi').textContent=(P[$('#o3').selectedIndex]||[])[1]||'';$('#o3').onchange=sh;sh();$('#co').scrollIntoView({behavior:'smooth'});
$('#o6').onclick=()=>{const v=i=>$('#o'+i).value.trim();if(!v(1)||!v(2)||!v(4))return toast('Fill name, Discord and reference');const id='OR-'+Math.random().toString(36).slice(2,7).toUpperCase();put('s_ord',[{id,item:x[0],price:x[1],name:v(1),discord:v(2),method:$('#o3').value,ref:v(4),msg:v(5),status:'pending',at:Date.now()},...ORD()]);burst();$('#co').innerHTML=`<div class="card" style="margin-top:16px"><h3>Order sent: ${id}</h3><p style="margin:0">Staff will verify your payment and confirm on Discord.</p></div>`}})}
function pSup(){const F=[['ticket','Open a ticket','Technical or account problems.','#apply/ticket'],['report','Report a player','Send evidence for staff to review.','#apply/report'],['appeal','Ban appeal','Ask for a second chance.','#apply/appeal'],['whitelist','Track application','Look up your decision with your ID.','#status']];
$('#app').innerHTML=pg('Support','Fast help from real staff.',`<div class="grid">${F.map(f=>`<a href="${f[3]}" style="text-decoration:none"><div class="card hv"><div class="ic">${IC[f[0]]}</div><h3>${f[1]}</h3><p style="margin:0">${f[2]}</p></div></a>`).join('')}</div><section class="sec"><h2>Supporters wall</h2>${wallH()}</section><p style="margin-top:18px">${DL()}</p>`)}
function contentUI(){const s=settings();return `<div class="card" style="max-width:640px"><label for="c1">Events (date | title | description, one per line)</label><textarea id="c1">${esc(s.ev)}</textarea><label for="c2">Team (name | role)</label><textarea id="c2">${esc(s.tm)}</textarea><label for="c3">Streamers (name | link)</label><textarea id="c3">${esc(s.st)}</textarea><p><button class="btn" id="cs">Save content</button></p></div>`}
const logA=m=>{const l=get('s_log',[]);l.unshift({at:Date.now(),m});put('s_log',l.slice(0,150))};
let AF={type:'all',st:'all',q:'',tab:'queue'};
const MG={event:['ev','Event Manager','date | title | description'],rules:['ru','Rules Manager','section | rule'],dept:['dp','Department Builder','name | description | question 1; question 2; question 3'],team:['tm','Team Manager','name | role'],illegal:['il','Illegal Manager','title | description'],gang:['gr','Gang Rosters','gang | leader | members'],store:['sh','Store Manager','item | price | description'],pay:['pm','Payment Gateway','method | instructions shown at checkout'],creator:['st','Creator Manager','name | channel link']};
const NAVG=[['OVERVIEW',[['logs','Audit Logs']]],['APPLICATIONS',[['queue','All Queues'],['orders','Orders']]],['MANAGEMENT',[['event','Event Manager'],['rules','Rules Manager'],['dept','Department Builder'],['team','Team Manager'],['illegal','Illegal Manager'],['gang','Gang Rosters'],['store','Store Manager'],['pay','Payment Gateway'],['wall','Supporters Wall'],['creator','Creator Manager']]],['SYSTEM',[['set','Settings']]]];
const ah=(t,d,b)=>`<div class="row" style="justify-content:space-between"><div><h2 style="margin:0;font-size:28px">${t}</h2><p class="note" style="margin:4px 0 14px">${d}</p></div>${b||''}</div>`;
function qUI(A){const q=AF.q.toLowerCase(),c=x=>A.filter(a=>a.status==x).length;
const Lr=A.filter(a=>(AF.type=='all'||a.type==AF.type)&&(AF.st=='all'||a.status==AF.st)&&(!q||(a.id+JSON.stringify(a.data)).toLowerCase().includes(q)));
const dc=[['all','All queues',IC.whitelist],...TYPES.map(t=>[t.id,t.name,IC[t.id]||IC.whitelist])].map(([id,n,ic])=>{const l=A.filter(a=>id=='all'||a.type==id);return `<button class="dc ${AF.type==id?'on':''}" data-dp="${id}">${ic}<b>${n}</b><span>${l.length}</span><em>${l.filter(a=>a.status=='pending').length} PND</em></button>`}).join('');
const mc=[['all','Total submissions',A.length],['pending','Pending review',c('pending')],['accepted','Accepted / approved',c('accepted')],['denied','Rejected',c('denied')]].map(([k,n,v])=>`<button class="mc ${k} ${AF.st==k?'on':''}" data-stt="${k}"><small>${n}</small><b>${v}</b></button>`).join('');
return ah('Application command queue','Live submission counter, department filters and decisions.','<button class="btn g s" data-t="logs">View audit logs</button>')+`<p class="sg">SELECT DEPARTMENT</p><div class="dg">${dc}</div><p class="sg">OVERALL STATUS METRICS</p><div class="dg mg">${mc}</div><div class="row" style="margin:14px 0"><input id="fq" placeholder="Search Discord, name, ID" value="${esc(AF.q)}" style="flex:1;min-width:180px"><select id="fd" style="width:auto"><option value="all">All departments</option>${TYPES.map(t=>`<option value="${t.id}" ${AF.type==t.id?'selected':''}>${t.name}</option>`).join('')}</select><select id="fs" style="width:auto">${['all','pending','accepted','denied'].map(x=>`<option ${AF.st==x?'selected':''}>${x}</option>`).join('')}</select></div><p class="note">SHOWING ${Lr.length} OF ${A.length} APPLICATIONS</p><div class="wrap">${Lr.length?`<table><tr><th>ID</th><th>Type</th><th>Discord</th><th>Sent</th><th>Status</th><th></th></tr>${Lr.map(a=>`<tr><td>${a.id}</td><td>${esc(a.typeName)}</td><td>${esc(a.data.discord)}</td><td>${fmt(a.at)}</td><td>${badge(a.status)}</td><td><button class="btn s g" data-v="${a.id}">Review</button></td></tr>`).join('')}</table>`:'<p>No applications match.</p>'}</div><div id="rv"></div>`}
function oUI(O){return ah('Orders','Verify store payments before they reach the supporters wall.')+`<div class="wrap">${O.length?`<table><tr><th>ID</th><th>Item</th><th>Name</th><th>Discord</th><th>Method</th><th>Reference</th><th>Status</th><th></th></tr>${O.map(o=>`<tr><td>${o.id}</td><td>${esc(o.item)} (${esc(o.price)})</td><td>${esc(o.name)}</td><td>${esc(o.discord)}</td><td>${esc(o.method)}</td><td>${esc(o.ref)}</td><td>${badge(o.status=='verified'?'accepted':o.status=='rejected'?'denied':'pending')}</td><td class="row"><button class="btn ok s" data-o="${o.id}" data-a="verified">Verify</button><button class="btn no s" data-o="${o.id}" data-a="rejected">Reject</button></td></tr>`).join('')}</table>`:'<p>No orders yet.</p>'}</div>`}
function wUI(O){const W=O.filter(o=>o.status=='verified');return ah('Supporters wall','Verified supporters shown on the public site.')+(W.length?`<div class="grid">${W.map(o=>`<div class="card"><h3>${esc(o.name)}</h3><p>${esc(o.item)} ${o.msg?'· '+esc(o.msg):''}</p><button class="btn no s" data-o="${o.id}" data-a="hidden">Remove</button></div>`).join('')}</div>`:'<p>Nothing verified yet. Verify orders under Orders.</p>')}
function lUI(){const l=get('s_log',[]);return ah('Audit logs','Every staff action in this browser.')+(l.length?`<div class="wrap"><table>${l.map(x=>`<tr><td>${fmt(x.at)}</td><td>${esc(x.m)}</td></tr>`).join('')}</table></div>`:'<p>No actions logged yet.</p>')}
function eUI(k){const m=MG[k];return ah(m[1],'One entry per line: '+m[2])+`<div class="card"><textarea id="ed" style="min-height:260px">${esc(settings()[m[0]])}</textarea><p><button class="btn" id="sv">Save</button></p></div>`}
function sUI(){const s=settings();return ah('Settings','Server details and application availability.')+`<div class="card" style="max-width:560px"><label for="s1">Server name</label><input id="s1" value="${esc(s.name)}"><label for="s2">Discord invite</label><input id="s2" value="${esc(s.discord)}"><label for="s3">Connect line</label><input id="s3" value="${esc(s.ip)}"><label for="s5">Players online</label><input id="s5" type="number" value="${s.pl}"><label for="s6">Max slots</label><input id="s6" type="number" value="${s.mx}"><label for="s7">Discord members</label><input id="s7" type="number" value="${s.dm}"><label for="s4">Admin password</label><input id="s4" value="${esc(s.pass)}"><label>Open application types</label>${TYPES.map(t=>`<label style="margin:4px 0"><input type="checkbox" class="oc" value="${t.id}" style="width:auto;margin-right:8px" ${s.closed.includes(t.id)?'':'checked'}>${t.name}</label>`).join('')}<p class="row"><button class="btn" id="ss">Save settings</button><button class="btn g" id="ex">Export JSON</button></p></div>`}
function ordAct(id,a){const O=ORD(),o=O.find(x=>x.id==id);if(!o)return;o.status=a;put('s_ord',O);logA('Order '+id+' '+a);toast('Order '+a);admin()}
function admin(){
if(!isAdmin()){$('#app').innerHTML=`<h2 style="margin-top:12px">Staff login</h2><div class="card" style="max-width:360px"><label for="pw">Password</label><input id="pw" type="password"><p><button class="btn" id="li">Log in</button></p><p class="note">Demo password: admin123. Change it under Settings.</p></div>`;
$('#li').onclick=()=>{if($('#pw').value===settings().pass){mem.adm=1;try{sessionStorage.setItem('adm','1')}catch(e){}logA('Staff login');nav('admin');admin()}else toast('Wrong password')};return}
syncT();const A=apps(),O=ORD(),t=AF.tab,po=O.filter(o=>o.status=='pending').length,pd=A.filter(a=>a.status=='pending').length;
const side=NAVG.map(([g,it])=>`<div class="sg">${g}</div>`+it.map(([k,v])=>`<button class="si ${t==k?'on':''}" data-t="${k}">${v}${k=='queue'&&pd?`<em>${pd}</em>`:''}${k=='orders'&&po?`<em>${po}</em>`:''}</button>`).join('')).join('');
const body=t=='queue'?qUI(A):t=='orders'?oUI(O):t=='wall'?wUI(O):t=='logs'?lUI():t=='set'?sUI():MG[t]?eUI(t):qUI(A);
$('#app').innerHTML=`<div class="adm"><aside class="side"><div class="lg2">${esc(settings().name)} ADMIN</div>${side}<button class="si" id="lo">Log out</button></aside><section class="am">${body}<p class="note" style="margin-top:28px">Demo mode: data is stored in this browser only. Connect a backend and real auth before going live.</p></section></div>`;
const g=i=>$('#'+i),qa=(q,f)=>document.querySelectorAll(q).forEach(f);
qa('[data-t]',b=>b.onclick=()=>{AF.tab=b.dataset.t;admin();scrollTo(0,0)});qa('[data-dp]',b=>b.onclick=()=>{AF.type=b.dataset.dp;admin()});qa('[data-stt]',b=>b.onclick=()=>{AF.st=b.dataset.stt;admin()});qa('[data-v]',b=>b.onclick=()=>review(b.dataset.v));qa('[data-o]',b=>b.onclick=()=>ordAct(b.dataset.o,b.dataset.a));
if(g('fq')){g('fq').onchange=e=>{AF.q=e.target.value;admin()};g('fd').onchange=e=>{AF.type=e.target.value;admin()};g('fs').onchange=e=>{AF.st=e.target.value;admin()}}
if(g('sv'))g('sv').onclick=()=>{const m=MG[AF.tab];put('s_set',{...settings(),[m[0]]:g('ed').value});logA(m[1]+' updated');syncT();toast('Saved')};
if(g('ss'))g('ss').onclick=()=>{put('s_set',{...settings(),pl:+g('s5').value||0,mx:+g('s6').value||128,dm:+g('s7').value||0,name:g('s1').value||SET0.name,discord:g('s2').value,ip:g('s3').value,pass:g('s4').value||'admin123',closed:[...document.querySelectorAll('.oc')].filter(x=>!x.checked).map(x=>x.value)});logA('Settings updated');toast('Settings saved');nav('admin')};
if(g('ex'))g('ex').onclick=()=>{const b=new Blob([JSON.stringify({apps:apps(),orders:ORD()},null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='export.json';a.click()};
g('lo').onclick=()=>{mem.adm=0;try{sessionStorage.removeItem('adm')}catch(e){}nav('admin');admin()};
}
function review(id){const a=apps().find(x=>x.id==id);if(!a)return;
$('#rv').innerHTML=`<div class="card" style="margin-top:16px"><h3>${esc(a.typeName)} · ${a.id} ${badge(a.status)}</h3><dl class="kv">${Object.entries(a.data).map(([k,v])=>`<dt>${esc(a.labels[k]||k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><label for="nt">Staff note (visible to applicant)</label><textarea id="nt">${esc(a.note)}</textarea><p class="row"><button class="btn ok s" data-d="accepted">Accept</button><button class="btn no s" data-d="denied">Deny</button><button class="btn g s" data-d="pending">Set pending</button><button class="btn g s" data-d="del">Delete</button></p></div>`;
$('#rv').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const d=b.dataset.d;let Lq=apps();if(d=='del'){Lq=Lq.filter(x=>x.id!=id)}else{const x=Lq.find(y=>y.id==id);x.status=d;x.note=$('#nt').value}put('s_apps',Lq);logA('Application '+id+' '+d);toast(d=='del'?'Deleted':'Saved: '+d);admin()})}
const RM=matchMedia('(prefers-reduced-motion:reduce)').matches;let fxI=0;
function fx(){
const a=$('#app');a.classList.remove('pg');void a.offsetWidth;a.classList.add('pg');
if(!fxI){fxI=1;const bar=document.createElement('div');bar.id='bar';const sp=document.createElement('div');sp.id='spot';document.body.append(bar,sp);
addEventListener('scroll',()=>{const y=scrollY,m=document.documentElement.scrollHeight-innerHeight;bar.style.transform=`scaleX(${m>0?y/m:0})`;const k=$('.sky');if(k&&!RM)k.style.setProperty('--sy',Math.min(y,700));$('#nav').classList.toggle('sc',y>20)},{passive:true});
addEventListener('pointermove',e=>{if(RM)return;sp.style.transform=`translate(${e.clientX-300}px,${e.clientY-300}px)`;const c=e.target.closest&&e.target.closest('.hv');if(c&&e.pointerType=='mouse'){const r=c.getBoundingClientRect();c.style.setProperty('--ry',((e.clientX-r.left)/r.width-.5)*10+'deg');c.style.setProperty('--rx',-((e.clientY-r.top)/r.height-.5)*10+'deg')}});
addEventListener('pointerout',e=>{const c=e.target.closest&&e.target.closest('.hv');if(c){c.style.setProperty('--rx','0deg');c.style.setProperty('--ry','0deg')}});
addEventListener('pointerdown',e=>{const b=e.target.closest&&e.target.closest('.btn,.cta');if(!b||RM)return;const r=b.getBoundingClientRect(),n=document.createElement('span');n.className='rp';n.style.left=e.clientX-r.left+'px';n.style.top=e.clientY-r.top+'px';b.append(n);setTimeout(()=>n.remove(),650)})}
if(RM)return;
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const t=e.target;t.classList.add('in');io.unobserve(t);if(t.tagName=='H2')scr(t);setTimeout(()=>{t.style.transitionDelay='';t.classList.add('done')},1000)}}),{threshold:.1});
a.querySelectorAll('.card,.sec>h2,.sec>p,.rg>div,details,.chip,.tick').forEach((el,i)=>{el.classList.add('rv');el.style.transitionDelay=(i%6)*70+'ms';io.observe(el)});
a.querySelectorAll('.chip b').forEach(b=>{if(!/^\d+$/.test(b.textContent))return;const n=+b.textContent,t0=performance.now();(function f(t){const p=Math.min((t-t0)/1200,1);b.textContent=Math.round(n*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(f)})(t0)});
}
const tx=()=>getComputedStyle(document.documentElement).getPropertyValue('--tx').trim()||'#fff';
const rgbOf=h=>{h=h.replace('#','');if(h.length==3)h=[...h].map(c=>c+c).join('');return [0,2,4].map(i=>parseInt(h.substr(i,2),16)).join(',')};
function scr(el){if(RM||el.children.length)return;const o=el.textContent,ch='!<>-_/[]{}=+*^?#';let f=0;const id=setInterval(()=>{f++;el.textContent=[...o].map((c,i)=>c==' '||i<o.length*f/22?c:ch[Math.random()*ch.length|0]).join('');if(f>=22){clearInterval(id);el.textContent=o}},38)}
function burst(x,y){if(RM)return;let c=$('#cf');if(!c){c=document.createElement('canvas');c.id='cf';c.width=innerWidth;c.height=innerHeight;document.body.append(c)}
const g=c.getContext('2d'),Q=[],X=x??innerWidth/2,Y=y??innerHeight*.4,K=[tx(),'#8c8c8c'];
for(let i=0;i<100;i++)Q.push({x:X,y:Y,vx:(Math.random()-.5)*15,vy:-Math.random()*14-3,s:3+Math.random()*6,r:Math.random()*6,vr:(Math.random()-.5)*.4,a:1,k:K[i%2]});
(function f(){g.clearRect(0,0,c.width,c.height);let n=0;Q.forEach(q=>{q.vy+=.35;q.x+=q.vx;q.y+=q.vy;q.vx*=.99;q.r+=q.vr;q.a-=.011;if(q.a>0){n++;g.save();g.globalAlpha=q.a;g.translate(q.x,q.y);g.rotate(q.r);g.fillStyle=q.k;g.fillRect(-q.s/2,-q.s/4,q.s,q.s/2);g.restore()}});if(n)requestAnimationFrame(f);else c.remove()})()}
function fx2(){if(RM)return;const a=$('#app');
a.querySelectorAll('.hero h1 em').forEach(e=>e.dataset.t=e.textContent);
const tk=a.querySelector('.tick');if(tk){const c=tk.cloneNode(true);c.className='tick rev';tk.after(c)}
const hp=a.querySelector('.hero>p');if(hp){const w=document.createElement('p');w.className='tw';w.innerHTML='<span></span><i></i>';hp.after(w);const sp=w.firstChild,ph=['Realism.','Immersion.','Resistance.','Your city. Your story.'];let i=0,j=0,d=0;(function t(){if(!document.body.contains(w))return;const s=ph[i];j+=d?-1:1;sp.textContent=s.slice(0,j);let dl=d?35:75;if(!d&&j==s.length){d=1;dl=1400}else if(d&&j==0){d=0;i=(i+1)%ph.length;dl=300}setTimeout(t,dl)})()}}
function fxG(){if(RM)return;
const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
const cv=document.createElement('canvas');cv.id='fxc';document.body.prepend(cv);const cx=cv.getContext('2d');
const dp=Math.min(devicePixelRatio||1,1.5),P=[];let W,H,mx=-999,my=-999,rx=0,ry=0,col=rgbOf(tx()),k=0;
const rs=()=>{W=innerWidth;H=innerHeight;cv.width=W*dp;cv.height=H*dp;cv.style.width=W+'px';cv.style.height=H+'px';cx.setTransform(dp,0,0,dp,0,0)};rs();addEventListener('resize',rs);
for(let i=0;i<(fine?64:30);i++)P.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.6+Math.random()*1.5,vx:(Math.random()-.5)*.25,vy:-.1-Math.random()*.3});
const w=document.createElement('div');w.id='wipe';w.innerHTML='<b class="lm"></b>';document.body.append(w);
const cc=document.createElement('div'),cr=document.createElement('div');cc.id='cur';cr.id='cur2';
if(fine){document.documentElement.classList.add('cc');document.body.append(cc,cr)}
const up=e=>{const t=e.target,c=t.closest&&t.closest('.card');if(c){const r=c.getBoundingClientRect();c.style.setProperty('--mx',e.clientX-r.left+'px');c.style.setProperty('--my',e.clientY-r.top+'px')}};
addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;const d=document.documentElement.style;d.setProperty('--px',(mx/innerWidth-.5)*2);d.setProperty('--py',(my/innerHeight-.5)*2);up(e);
if(fine){cc.style.transform=`translate(${mx}px,${my}px)`;cr.classList.toggle('h',!!(e.target.closest&&e.target.closest('a,button,.hv,summary')));const b=e.target.closest&&e.target.closest('.btn,.cta');if(b){const r=b.getBoundingClientRect();b.style.translate=`${(mx-r.left-r.width/2)*.22}px ${(my-r.top-r.height/2)*.3}px`}}},{passive:true});
addEventListener('pointerout',e=>{const b=e.target.closest&&e.target.closest('.btn,.cta');if(b)b.style.translate=''});
addEventListener('pointerdown',e=>{const t=document.createElement('i');t.className='tap';t.style.left=e.clientX+'px';t.style.top=e.clientY+'px';document.body.append(t);setTimeout(()=>t.remove(),700)});
let ly=0;addEventListener('scroll',()=>{const y=scrollY,n=$('#nav');n.style.transform=y>ly&&y>260?'translateY(-110%)':'';ly=y;const h=$('.hero');if(h)h.style.setProperty('--hy',Math.min(y,600))},{passive:true});
(function loop(){requestAnimationFrame(loop);if(document.hidden)return;if(!(k++%120))col=rgbOf(tx());
cx.clearRect(0,0,W,H);
for(let i=0;i<P.length;i++){const p=P[i];p.x+=p.vx;p.y+=p.vy;const dx=p.x-mx,dy=p.y-my,dd=dx*dx+dy*dy;if(dd<14400){const f=(1-Math.sqrt(dd)/120)*.8;p.x+=dx*f*.05;p.y+=dy*f*.05}
if(p.y<-10){p.y=H+10;p.x=Math.random()*W}if(p.x<-10)p.x=W+10;if(p.x>W+10)p.x=-10;
cx.fillStyle=`rgba(${col},.55)`;cx.beginPath();cx.arc(p.x,p.y,p.r,0,6.283);cx.fill();
for(let j=i+1;j<P.length;j++){const q=P[j],ex=p.x-q.x,ey=p.y-q.y,d=ex*ex+ey*ey;if(d<12100){cx.strokeStyle=`rgba(${col},${(1-Math.sqrt(d)/110)*.16})`;cx.lineWidth=.7;cx.beginPath();cx.moveTo(p.x,p.y);cx.lineTo(q.x,q.y);cx.stroke()}}
if(dd<27000){cx.strokeStyle=`rgba(${col},${(1-Math.sqrt(dd)/164)*.35})`;cx.beginPath();cx.moveTo(p.x,p.y);cx.lineTo(mx,my);cx.stroke()}}
if(fine){rx+=(mx-rx)*.18;ry+=(my-ry)*.18;cr.style.transform=`translate(${rx}px,${ry}px)`}})()}
fxG();route();
